version: "3"

services:
    api:
        build: .
        container_name: api
        restart: always
        command: uvicorn funnyapi.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - 8000:8000
            - 7999:7999 # for remote debugging
        env_file:
            - ./api.env
        volumes:
            - ./src/funnyapi:/code/funnyapi
        networks:
            - funnyapi
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: database
        restart: always
        ports:
            - 3306:3306
        env_file:
            - ./db.env
        volumes:
            - ./db_data:/var/lib/mysql
            - ./database_init.sql:/docker-entrypoint-initdb.d/001_init_db.sql
        networks:
            - funnyapi

networks:
    funnyapi:
        name: funny-api
